apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-appset
spec:
  generators:
    - list:
        elements:
          - name: nginx-deployment
            repoURL: https://github.com/Rajesh-Sangepu/ArogcdProjects.git         #deployment
            targetRevision: HEAD
            path: ApplicationSet/Applicationsetfiles/app1
          - name: nginx-service
            repoURL: https://github.com/Rajesh-Sangepu/ArogcdProjects.git          #service
            targetRevision: HEAD
            path: ApplicationSet/Applicationsetfiles/app2
  template:
    metadata:
      name: "{{ .name }}-app"
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
