apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app2
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Rajesh-Sangepu/ArogcdProjects.git
    targetRevision: HEAD
    path: ApplicationSet/Applicationsetfiles/app3

  destination:
    server: https://kubernetes.default.svc
    namespace: my-target-namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
